### ISSUE TITLE
Infografia hilos

### ISSUE THREAD

**Issue by DuilioAquino10** [SistemasTecTlaxiaco/infografia-de-hilos-DuilioAquino10#2]
[Aquino Lopez Duilio Ruben hilos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-DuilioAquino10/files/6461073/Aquino.Lopez.Duilio.Ruben.hilos.pdf)

**Comment by Valentiin01** [comment]
calificación: 20 ,buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado
